#!/usr/bin/env sh
${IDRIS:-idris} --consolewidth 80 $@ reg018a.idr --check
${IDRIS:-idris} --consolewidth 80 $@ reg018b.idr --check
${IDRIS:-idris} --consolewidth 80 $@ reg018c.idr --check
${IDRIS:-idris} --consolewidth 80 $@ reg018d.idr --check
rm *.ibc
