#!/usr/bin/env bash
idris --consolewidth 80 $@ reg018a.idr --check
idris --consolewidth 80 $@ reg018b.idr --check
idris --consolewidth 80 $@ reg018c.idr --check
idris --consolewidth 80 $@ reg018d.idr --check
rm *.ibc
