#!/bin/bash
if [[ $@ == "--target node" ]]; then
  idris --target node test005.idr -o test005.js
  node test005
  rm -f test005.js *.ibc
else
  idris $@ test005.idr -o test005
  ./test005
  rm -f test005 test005.ibc
fi
