<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>idr</string>
	</array>
	<key>name</key>
	<string>Idris</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|do|let|in|data|codata|record|dsl|import)\b</string>
			<key>name</key>
			<string>keyword.control.idris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(impossible|case|of|total|partial|mutual|infix|infixl|infixr)\b</string>
			<key>name</key>
			<string>keyword.control.idris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(where|with|syntax|proof|postulate|using|namespace|class|instance)\b</string>
			<key>name</key>
			<string>keyword.control.idris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(public|private|abstract|implicit)\b</string>
			<key>name</key>
			<string>keyword.control.idris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Type|Int|Integer|Float64|Char|String|Ptr|Bits8|Bits16|Bits32|Bits64)\b</string>
			<key>name</key>
			<string>keyword.other.idris</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(S|O)\b</string>
			<key>name</key>
			<string>constant.numeric.idris</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>integers</string>
			<key>match</key>
			<string>\b([0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))\b</string>
			<key>name</key>
			<string>constant.numeric.idris</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>floats</string>
			<key>match</key>
			<string>\b([0-9]+\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.float.idris</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line comment</string>
			<key>match</key>
			<string>(--).*$
?</string>
			<key>name</key>
			<string>comment.line.idris</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{-</string>
			<key>comment</key>
			<string>Block comment</string>
			<key>end</key>
			<string>-\}</string>
			<key>name</key>
			<string>comment.block.idris</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.idris</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.idris</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.idris</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.idris</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
	</dict>
	<key>scopeName</key>
	<string>source.idris</string>
	<key>uuid</key>
	<string>4dd16092-ffa5-4ba4-8075-e5da9f368a72</string>
</dict>
</plist>
