test:
	perl ./runtest.pl all

test_java:
	perl ./runtest.pl all --target Java

test_js:
	@perl ./runtest.pl reg001 --target node
	@perl ./runtest.pl reg002 --target node
	@perl ./runtest.pl reg003 --target node
	@perl ./runtest.pl reg004 --target node
	@perl ./runtest.pl reg004 --target node
	@perl ./runtest.pl reg005 --target node
	@perl ./runtest.pl reg006 --target node
	@perl ./runtest.pl reg007 --target node
	@perl ./runtest.pl reg008 --target node
	@perl ./runtest.pl reg009 --target node
	@perl ./runtest.pl reg010 --target node
	@perl ./runtest.pl reg011 --target node
	@perl ./runtest.pl reg012 --target node
	@perl ./runtest.pl reg013 --target node
	@perl ./runtest.pl reg014 --target node
	@perl ./runtest.pl reg015 --target node
	@#perl ./runtest.pl reg016 --target node
	@perl ./runtest.pl reg017 --target node
	@perl ./runtest.pl reg018 --target node
	@perl ./runtest.pl reg019 --target node
	@perl ./runtest.pl test001 --target node
	@perl ./runtest.pl test002 --target node
	@perl ./runtest.pl test003 --target node
	@#perl ./runtest.pl test004 --target node
	@perl ./runtest.pl test005 --target node
	@perl ./runtest.pl test006 --target node
	@perl ./runtest.pl test007 --target node
	@perl ./runtest.pl test008 --target node
	@perl ./runtest.pl test009 --target node
	@perl ./runtest.pl test010 --target node
	@perl ./runtest.pl test011 --target node
	@perl ./runtest.pl test012 --target node
	@perl ./runtest.pl test013 --target node
	@#perl ./runtest.pl test014 --target node
	@perl ./runtest.pl test015 --target node
	@perl ./runtest.pl test016 --target node
	@perl ./runtest.pl test017 --target node
	@#perl ./runtest.pl test018 --target node
	@perl ./runtest.pl test019 --target node
	@perl ./runtest.pl test020 --target node
	@#perl ./runtest.pl test021 --target node
	@perl ./runtest.pl test022 --target node
	@perl ./runtest.pl test023 --target node
	@perl ./runtest.pl test024 --target node
	@#perl ./runtest.pl test025 --target node
	@perl ./runtest.pl test026 --target node
	@perl ./runtest.pl test027 --target node
	@perl ./runtest.pl test028 --target node

update:
	perl ./runtest.pl all -u

diff:
	perl ./runtest.pl all -d

distclean:
	rm -f *~
	rm -f */output
