#!/usr/bin/env bash

${IDRIS:-idris} $@ --nobanner --nocolour --quiet --port none <<!
:load reg003.idr
:load reg003a.idr
:load reg006.idr
:load reg007.lidr
:load reg010.idr
:load reg018a.idr
:load reg018b.idr
:load reg018c.idr
:load reg018d.idr
:load reg023.idr
:load reg028.idr
:load reg028a.idr
:load reg034.idr
:load reg035.idr
:load reg035a.lidr
:load reg035b.idr
:load reg044.idr
:load reg049.idr
:load working.idr
:load badbangop.idr
:load baddoublebang.idr
:load reg054.idr
:load reg055.idr
:load reg055a.idr
:load reg056.idr
:load reg068.idr
:load reg069.idr
:load reg070.idr
:load reg076.idr
:load reg077.idr
:load DoubleEquality.idr
!

rm -f *.ibc
