#!/usr/bin/env bash

${IDRIS:-idris} $@ --nobanner --nocolour --quiet <<!
:load reg003.idr
:load reg003a.idr
:load reg006.idr
:load reg007.lidr
:load reg010.idr
:load reg018a.idr
:load reg018b.idr
:load reg018c.idr
:load reg018d.idr
:load reg023.idr
:load reg028.idr
:load reg028a.idr
!

rm -f *.ibc
