#!/usr/bin/env bash
idris --nocolour --consolewidth 80 $@ unique001.idr -o unique001
./unique001
idris --nocolour --consolewidth 80 $@ unique001a.idr --check
idris --nocolour --consolewidth 80 $@ unique001b.idr --check
idris --nocolour --consolewidth 80 $@ unique001c.idr --check
idris --nocolour --consolewidth 80 $@ unique001d.idr --check
idris --nocolour --consolewidth 80 $@ unique001e.idr --check
rm -f unique001 *.ibc
