#!/usr/bin/env bash
${IDRIS:-idris} --nocolour --consolewidth 80 $@ unique001.idr -o unique001
./unique001
${IDRIS:-idris} --nocolour --consolewidth 80 $@ unique001a.idr --check
${IDRIS:-idris} --nocolour --consolewidth 80 $@ unique001b.idr --check
${IDRIS:-idris} --nocolour --consolewidth 80 $@ unique001c.idr --check
${IDRIS:-idris} --nocolour --consolewidth 80 $@ unique001d.idr --check
${IDRIS:-idris} --nocolour --consolewidth 80 $@ unique001e.idr --check
rm -f unique001 *.ibc
