resolver: lts-7.10

packages:
  - location : .
  - location : core
    extra-dep: true
  - location : codegen/idris-codegen-c
    extra-dep: true

flags:
  idris:
    FFI:       true
    GMP:       true
    codegen_C: false

extra-deps:
  - libffi-0.1
  - safe-0.3.9
nix:
  enable: false
  shell-file: stack-shell.nix
