#recheck extra-deps next on resolver or cabal file change
resolver: lts-11.3

packages:
  - location: .

extra-deps: []

flags:
  idris:
    FFI: true
    GMP: true

ghc-options:
  idris: -fwarn-unused-imports -fwarn-unused-binds

nix:
  enable: false
  shell-file: stack-shell.nix
