#recheck extra-deps next on resolver or cabal file change
resolver: lts-12.21

packages:
  - location: .

extra-deps:
  - megaparsec-7.0.4
  - parser-combinators-1.0.0
  - network-2.8.0.0


flags:
  idris:
    FFI: true
    GMP: true

ghc-options:
  idris: -fwarn-unused-imports -fwarn-unused-binds

nix:
  enable: false
  shell-file: stack-shell.nix
