resolver: lts-7.10

packages:
  - location : .
  - location : core
    extra-dep: true
  - location : codegen/idris-codegen-c
    extra-dep: true
  - location : codegen/idris-codegen-javascript
    extra-dep: true

flags:
  idris:
    FFI               : true
    codegen_C         : false
    codegen_JavaScript: false
  idris-codegen-c:
    GMP: true

extra-deps:
  - libffi-0.1
  - safe-0.3.9
nix:
  enable: false
  shell-file: stack-shell.nix
