resolver: lts-5.11

packages:
  - '.'

flags:
  idris:
    FFI: true
    GMP: true

extra-include-dirs:
  - /usr/local/opt/gmp/include/gmp

extra-lib-dirs:
  - /usr/local/opt/gmp/lib

extra-deps:
  - libffi-0.1

nix:
  enable: false
  shell-file: stack-shell.nix
