#recheck extra-deps next on resolver or cabal file change
resolver: nightly-2017-10-23

packages:
  - location: .

flags:
  idris:
    FFI: true
    GMP: true

ghc-options:
  idris: -fwarn-unused-imports -fwarn-unused-binds

nix:
  enable: false
  shell-file: stack-shell.nix
