#!/usr/bin/env sh
${IDRIS:-idris} --consolewidth 80 $@ --check test017.idr
${IDRIS:-idris} --consolewidth 80 $@ --check test017a.idr
${IDRIS:-idris} --consolewidth 80 $@ --check test017b.idr
rm -f *.ibc
