#!/usr/bin/env bash
${IDRIS:-idris} --nocolour --consolewidth 80 --check reg035.idr
${IDRIS:-idris} --nocolour --consolewidth 80 --check reg035a.lidr
${IDRIS:-idris} --nocolour --consolewidth 80 --check reg035b.idr
rm -f *.ibc
