#!/bin/bash
if [[ $@ == "--target node" ]]; then
  idris --target node test009.idr -o test009.js
  node test009.js
  rm -f test009.js *.ibc
else
  idris $@ test009.idr -o test009
  ./test009
  rm -f test009 test009.ibc
fi
