#!/bin/bash
if [[ $@ == "--target node" ]]; then
  idris reg016.idr --target node -o reg016.js
  node reg016.js
  rm -f reg016.js *.ibc
else
  idris $@ reg016.idr -o reg016
  ./reg016
  rm -f reg016 *.ibc
fi
