#!/bin/bash
idris $@ test003a.lidr -o test003a.java --target Java
idris $@ test003.lidr -o test003.java --target Java
export CLASSPATH=../../java/idris.jar:$CLASSPATH
javac test003.java
java test003
rm -f test003.java *.class
