#!/usr/bin/env bash
${IDRIS:-idris} $@ --build test-pkg.ipkg
rm -f  *.ibc
${IDRIS:-idris} $@ --build test-pkg.ipkg --quiet
${IDRIS:-idris} $@ --build test-pkg.ipkg --logging-categories "elab" --log 1
