#!/usr/bin/env bash

${IDRIS:-idris} --nobanner --nocolour --quiet <<!
:load unique001a.idr
:load unique001b.idr
:load unique001c.idr
:load unique001d.idr
:load unique001e.idr
:load unique002.idr
:load unique002a.idr
!

rm -f *.ibc
