#!/bin/bash
idris $@ test015.idr -o test015.java --target Java
for RTS in ../../java/target/idris-*.jar; do
    export CLASSPATH=$RTS:$CLASSPATH
done;
javac test015.java
java test015
rm -f test015.java *.class
