#!/usr/bin/env sh
${IDRIS:-idris} --consolewidth 80 $@ --check test010.idr
${IDRIS:-idris} --consolewidth 80 $@ --check test010a.idr
${IDRIS:-idris} --consolewidth 80 $@ --check test010b.idr

rm -f *.ibc
