#!/bin/bash
if [[ $@ == "--target node" ]]; then
  idris --target node test011.idr -o test011.js
  node test011.js
  rm -f test011.js *.ibc
else
  idris $@ test011.idr -o test011
  ./test011
  rm -f test011 test011.ibc
fi
