#!/bin/bash
idris $@ test001.idr -o test001.java --target Java
for RTS in ../../java/target/idris-*.jar; do
    export CLASSPATH=$RTS:$CLASSPATH
done;
javac test001.java
java test001
rm -f test001.java *.class
