build: .PHONY
	$(MAKE) -C prelude build
	$(MAKE) -C base build
	$(MAKE) -C effects build
	$(MAKE) -C javascript build


install: .PHONY
	$(MAKE) -C prelude install
	$(MAKE) -C base install
	$(MAKE) -C effects install
	$(MAKE) -C javascript install

clean: .PHONY
	$(MAKE) -C prelude clean
	$(MAKE) -C base clean
	$(MAKE) -C effects clean
	$(MAKE) -C javascript clean
        
.PHONY:
