#!/usr/bin/env bash

idris --consolewidth 80 $@ Main.idr --nocolour --check && echo MAIN-PASS
idris --consolewidth 80 $@ Faulty.idr --nocolour --check && echo FAULTY-PASS
idris --consolewidth 80 $@ Multiple.idr --nocolour --check && echo MULTIPLE-PASS


rm -f *.ibc B/*.ibc 
