#!/bin/bash
idris $@ reg004.idr -o reg004.java --target Java
for RTS in ../../java/target/idris-*.jar; do
  export CLASSPATH=$RTS:$CLASSPATH
done;
javac reg004.java
java reg004
rm -f reg004.java *.class
