#!/bin/bash
idris $@ test004.idr -o test004.java --target Java
for RTS in ../../java/target/idris-*.jar; do
    export CLASSPATH=$RTS:$CLASSPATH
done;
javac test004.java
java test004
rm -f test004.java *.class
