#!/usr/bin/env bash
idris $@ -p pruviloj --nocolour --check --consolewidth 70 Tacs.idr
idris $@ -p pruviloj --nocolour --check --consolewidth 70 AgdaStyleReflection.idr
# Disabled due to excess memory consumption
# idris $@ -p pruviloj --nocolour --check --consolewidth 70 Deriving.idr
rm -f *.ibc
