#!/bin/bash
idris -p effects $@ test021.idr -o test021.java --target Java
idris -p effects $@ test021a.idr -o test021a.java --target Java
for RTS in ../../java/target/idris-*.jar; do
    export CLASSPATH=$RTS:$CLASSPATH
done;
javac test021.java
java test021
javac test021a.java
java test021a
rm -f test021.java test021a.java *.class
