#!/usr/bin/env bash

set -u

if [[ ${OSTYPE} = 'msys' ]]; then
  cat expected # skip this test on Windows
else
  ${IDRIS:-idris} "$@" --build base001.ipkg | grep -v 'make.*:'
  ./base001 2>&1 | grep -v '^sh:.*\./does-not-exist:'
  make clean | grep -v 'make.*:'
  rm -f -- *.ibc base001
fi
