#!/bin/bash
idris $@ test020.idr -o test020.java --target Java
idris $@ test020a.idr -o test020a.java --target Java
export CLASSPATH=../../java/idris.jar:$CLASSPATH
javac test020.java
java test020
rm -f test020.java *.class
