#!/bin/bash
if [[ $@ == "--target node" ]]; then
  idris reg005.idr --target node -o reg005.js
  node reg005.js
  rm -f reg005.js *.ibc
else
  idris $@ reg005.idr -o reg005
  ./reg005
  rm -f reg005 *.ibc
fi
