#!/bin/bash
idris $@ reg005.idr -o reg005.java --target Java
for RTS in ../../java/target/idris-*.jar; do
  export CLASSPATH=$RTS:$CLASSPATH
done;
javac reg005.java
java reg005
rm -f reg005.java *.class
